function hp = time_plot(x,fs,sig_name)
%TIME_PLOT -- print to png signal in time domian.

N = length(x);
time_line = (0:N-1)/fs;

Width=round(680);
Height=round(220);
figure('Position',[100 100 100+Width 100+Height]);

FontSize = 12;

hp = plot(time_line,x);
xlim([time_line(1) time_line(end)]);
hXLabel = xlabel('Время \it{t}, \rm{c}');
hYLabel = ylabel('Нормированная амплитуда, \it{x}\rm{(}\it{t}\rm{)}');

set (gca                    ,...
        'FontName', 'Helvetica',...
        'FontSize', FontSize);

set ([hXLabel hYLabel]      ,...
        'FontSize', FontSize,...
        'FontName', 'Times New Roman');
    
set(gca, ...
        'Box'       ,'off'          ,...
        'TickDir'   ,'out'          ,...
        'TickLength',[0.02,0.02]    ,...
        'XMinorTick','on'           ,...
        'YMinorTick','on'           ,...
        'YGrid'     ,'on'           ,...
        'XGrid'     ,'on'           ,...
        'XColor'    ,[0.1 0.1 0.1]  ,...
        'YColor'    ,[0.1 0.1 0.1]  ,...
        ...'XTick'     ,round((Lim(1):0.50:Lim(2))*10)/10        ,...
    ...     'YTick'     ,-0.6:0.3:0.6       ,...
    ...     'YTick'     ,-0.07:0.02:0.07        ,...
        'FontSize', FontSize             ,...
        'LineWidth' ,1.5);

    %% Print png

set(gcf, 'PaperPositionMode', 'auto');
FileName = [sig_name '_time_plot.png'];
print('-dpng', '-zbuffer','-r300',FileName);
end

